// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Proyecto_2020_1.Data;

namespace Proyecto_2020_1.Migrations
{
    [DbContext(typeof(GranjaContexto))]
    [Migration("20200308183843_inicial")]
    partial class inicial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.2");

            modelBuilder.Entity("Proyecto_2020_1.Models.Granja", b =>
                {
                    b.Property<int>("MadreId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Corral")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Raza")
                        .HasColumnType("TEXT");

                    b.HasKey("MadreId");

                    b.ToTable("granjas");
                });
#pragma warning restore 612, 618
        }
    }
}
